### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by fieryo** [miyu1/iCalLibrary#1]
Is iCalLibrary under MIT license?

**Comment by miyu1** [comment]
I haven't yet thought about license of this code.
I think MIT license is OK.
I will add license.txt in a couple of days. please wait.

**Comment by fieryo** [comment]
Adding MIT license would be great. Thanks.

**Comment by miyu1** [comment]
I added LICENSE file and modified README.md .

**Comment by fieryo** [comment]
Thank you.
